export const SUBJECT_CHOICES = ['math', 'it'] as const;

export const TOPIC_TO_SUBJECT = {
  linear_algebra: 'math',
  calculus: 'math',
  geometry: 'math',
  trigonometry: 'math',
  probability: 'math',
  statistics: 'math',
  discrete_structures: 'math',
  programming: 'it',
  data_structures: 'it',
  algorithms: 'it',
  databases: 'it',
} as const;

const CANONICAL_CONCEPT_TO_TOPIC = {
  vector_operations: 'linear_algebra',
  dot_product_and_projections: 'linear_algebra',
  matrix_operations: 'linear_algebra',
  matrix_inverse_and_systems: 'linear_algebra',
  determinant_as_scaling: 'linear_algebra',
  eigenvalues_and_eigenvectors_basics: 'linear_algebra',
  linear_transformations_in_2d: 'linear_algebra',
  limit_by_direct_substitution: 'calculus',
  limit_by_factoring_and_cancellation: 'calculus',
  derivative_from_first_principles: 'calculus',
  differentiation_power_rule: 'calculus',
  definite_integral_as_area: 'calculus',
  antiderivative_basic_rules: 'calculus',
  chain_rule_for_composite_functions: 'calculus',
  taylor_polynomial_approximation: 'calculus',
  triangle_angle_and_side_relations: 'geometry',
  triangle_similarity: 'geometry',
  circle_arcs_and_sectors: 'geometry',
  circle_theorems: 'geometry',
  distance_and_midpoint_in_plane: 'geometry',
  line_equation_and_slope: 'geometry',
  rigid_transformations_2d: 'geometry',
  surface_area_and_volume: 'geometry',
  right_triangle_trig_ratios: 'trigonometry',
  applying_trig_ratios: 'trigonometry',
  pythagorean_and_quotient_identities: 'trigonometry',
  angle_sum_and_double_angle_identities: 'trigonometry',
  unit_circle_special_angles: 'trigonometry',
  inverse_trig_basic_values: 'trigonometry',
  random_experiment_and_outcomes: 'probability',
  sample_space: 'probability',
  events_and_set_operations: 'probability',
  mutually_exclusive_events: 'probability',
  independent_events: 'probability',
  complementary_event: 'probability',
  classical_probability: 'probability',
  empirical_probability: 'probability',
  conditional_probability: 'probability',
  addition_rule: 'probability',
  multiplication_rule: 'probability',
  total_probability_theorem: 'probability',
  bayes_theorem: 'probability',
  modeling_discrete_random_variables: 'probability',
  modeling_continuous_random_variables: 'probability',
  probability_mass_function: 'probability',
  probability_density_function: 'probability',
  cumulative_distribution_func: 'probability',
  expected_value: 'probability',
  variance: 'probability',
  standard_deviation: 'probability',
  median_rv: 'probability',
  mode_rv: 'probability',
  bernoulli_distribution: 'probability',
  binomial_distribution: 'probability',
  poisson_distribution: 'probability',
  uniform_distribution: 'probability',
  normal_distribution_probabilities: 'probability',
  standard_normal_z_scores: 'probability',
  exponential_distribution: 'probability',
  law_of_large_numbers: 'probability',
  central_limit_theorem: 'probability',
  population: 'statistics',
  sample: 'statistics',
  sample_mean: 'statistics',
  sample_variance: 'statistics',
  adjusted_sample_variance: 'statistics',
  point_estimators: 'statistics',
  unbiasedness: 'statistics',
  confidence_interval_for_mean: 'statistics',
  confidence_level: 'statistics',
  margin_of_error: 'statistics',
  null_hypothesis: 'statistics',
  alternative_hypothesis: 'statistics',
  type_i_error: 'statistics',
  type_ii_error: 'statistics',
  significance_level: 'statistics',
  p_value: 'statistics',
  critical_region: 'statistics',
  pearson_correlation: 'statistics',
  simple_linear_regression_line: 'statistics',
  ordinary_least_squares_fit: 'statistics',
  coefficient_of_determination_r_squared: 'statistics',
  truth_tables_and_connectives: 'discrete_structures',
  logical_equivalence: 'discrete_structures',
  predicates_quantifiers: 'discrete_structures',
  rules_of_inference: 'discrete_structures',
  direct_and_contrapositive_proofs: 'discrete_structures',
  mathematical_induction: 'discrete_structures',
  set_theory_basics: 'discrete_structures',
  function_types_and_mappings: 'discrete_structures',
  relation_properties: 'discrete_structures',
  equivalence_relations: 'discrete_structures',
  partial_orders: 'discrete_structures',
  counting_principles: 'discrete_structures',
  permutations_combinations: 'discrete_structures',
  pigeonhole_principle: 'discrete_structures',
  inclusion_exclusion: 'discrete_structures',
  recurrence_relations: 'discrete_structures',
  graphs_vertices_edges_and_degrees: 'discrete_structures',
  graph_isomorphism: 'discrete_structures',
  graph_connectivity: 'discrete_structures',
  euler_hamilton_circuits: 'discrete_structures',
  mathematical_tree_properties: 'discrete_structures',
  graph_coloring: 'discrete_structures',
  group_operation_axioms: 'discrete_structures',
  ring_and_field_properties: 'discrete_structures',
  boolean_algebra_basics: 'discrete_structures',
  variables_and_assignment: 'programming',
  expressions_and_type_conversion: 'programming',
  conditional_branching: 'programming',
  loop_control: 'programming',
  functions_and_returns: 'programming',
  function_parameters_and_scope: 'programming',
  classes_and_objects: 'programming',
  recursion_base_and_recursive_case: 'programming',
  array_indexing_and_update: 'data_structures',
  array_traversal_and_aggregation: 'data_structures',
  linked_list_insert_delete: 'data_structures',
  stack_and_queue_operations: 'data_structures',
  tree_traversal: 'data_structures',
  binary_search_tree_operations: 'data_structures',
  graph_representation_and_traversal: 'data_structures',
  hash_table_lookup_and_collisions: 'data_structures',
  big_o_growth_rates: 'algorithms',
  linear_and_binary_search: 'algorithms',
  elementary_sorting: 'algorithms',
  divide_and_conquer_sorting: 'algorithms',
  dynamic_programming_state_transitions: 'algorithms',
  greedy_choice_and_local_optima: 'algorithms',
  relational_tables_and_keys: 'databases',
  primary_and_foreign_keys: 'databases',
  select_filter_and_project: 'databases',
  sql_joins: 'databases',
  normalization_to_3nf: 'databases',
  index_lookup_tradeoffs: 'databases',
  transaction_commit_rollback: 'databases',
  acid_properties: 'databases',
} as const;

const LEGACY_CONCEPT_TO_CANONICAL = {
  vectors: 'vector_operations',
  matrices: 'matrix_operations',
  determinants: 'determinant_as_scaling',
  eigenvalues_eigenvectors: 'eigenvalues_and_eigenvectors_basics',
  linear_transformations: 'linear_transformations_in_2d',
  limits: 'limit_by_direct_substitution',
  derivatives: 'derivative_from_first_principles',
  integrals: 'definite_integral_as_area',
  chain_rule: 'chain_rule_for_composite_functions',
  taylor_series: 'taylor_polynomial_approximation',
  triangles: 'triangle_angle_and_side_relations',
  circles: 'circle_arcs_and_sectors',
  coordinate_geometry: 'distance_and_midpoint_in_plane',
  transformations: 'rigid_transformations_2d',
  solid_geometry: 'surface_area_and_volume',
  trig_ratios: 'right_triangle_trig_ratios',
  trig_identities: 'pythagorean_and_quotient_identities',
  unit_circle: 'unit_circle_special_angles',
  inverse_trig: 'inverse_trig_basic_values',
  random_experiment: 'random_experiment_and_outcomes',
  event: 'events_and_set_operations',
  discrete_random_variable: 'modeling_discrete_random_variables',
  continuous_random_variable: 'modeling_continuous_random_variables',
  normal_distribution: 'normal_distribution_probabilities',
  standard_normal_dist: 'standard_normal_z_scores',
  point_estimation: 'point_estimators',
  confidence_interval: 'confidence_interval_for_mean',
  simple_linear_regression: 'simple_linear_regression_line',
  ordinary_least_squares: 'ordinary_least_squares_fit',
  coefficient_of_determination: 'coefficient_of_determination_r_squared',
  propositional_logic: 'truth_tables_and_connectives',
  proof_methods: 'direct_and_contrapositive_proofs',
  function_mappings: 'function_types_and_mappings',
  graph_models: 'graphs_vertices_edges_and_degrees',
  algebraic_groups: 'group_operation_axioms',
  rings_and_fields: 'ring_and_field_properties',
  variables: 'variables_and_assignment',
  control_flow: 'conditional_branching',
  functions: 'functions_and_returns',
  oop: 'classes_and_objects',
  recursion: 'recursion_base_and_recursive_case',
  arrays: 'array_indexing_and_update',
  linked_lists: 'linked_list_insert_delete',
  stacks_queues: 'stack_and_queue_operations',
  trees: 'tree_traversal',
  graphs: 'graph_representation_and_traversal',
  hash_tables: 'hash_table_lookup_and_collisions',
  big_o: 'big_o_growth_rates',
  sorting: 'elementary_sorting',
  searching: 'linear_and_binary_search',
  dynamic_programming: 'dynamic_programming_state_transitions',
  greedy: 'greedy_choice_and_local_optima',
  relational_model: 'relational_tables_and_keys',
  sql: 'select_filter_and_project',
  normalization: 'normalization_to_3nf',
  indexing: 'index_lookup_tradeoffs',
  transactions: 'transaction_commit_rollback',
} as const;

export const CONCEPT_TO_TOPIC = {
  vectors: 'linear_algebra',
  matrices: 'linear_algebra',
  determinants: 'linear_algebra',
  eigenvalues_eigenvectors: 'linear_algebra',
  linear_transformations: 'linear_algebra',
  limits: 'calculus',
  derivatives: 'calculus',
  integrals: 'calculus',
  chain_rule: 'calculus',
  taylor_series: 'calculus',
  triangles: 'geometry',
  circles: 'geometry',
  coordinate_geometry: 'geometry',
  transformations: 'geometry',
  solid_geometry: 'geometry',
  trig_ratios: 'trigonometry',
  trig_identities: 'trigonometry',
  unit_circle: 'trigonometry',
  inverse_trig: 'trigonometry',
  random_experiment: 'probability',
  sample_space: 'probability',
  event: 'probability',
  mutually_exclusive_events: 'probability',
  independent_events: 'probability',
  complementary_event: 'probability',
  classical_probability: 'probability',
  empirical_probability: 'probability',
  conditional_probability: 'probability',
  addition_rule: 'probability',
  multiplication_rule: 'probability',
  total_probability_theorem: 'probability',
  bayes_theorem: 'probability',
  discrete_random_variable: 'probability',
  continuous_random_variable: 'probability',
  probability_mass_function: 'probability',
  probability_density_function: 'probability',
  cumulative_distribution_func: 'probability',
  expected_value: 'probability',
  variance: 'probability',
  standard_deviation: 'probability',
  median_rv: 'probability',
  mode_rv: 'probability',
  bernoulli_distribution: 'probability',
  binomial_distribution: 'probability',
  poisson_distribution: 'probability',
  uniform_distribution: 'probability',
  normal_distribution: 'probability',
  standard_normal_dist: 'probability',
  exponential_distribution: 'probability',
  law_of_large_numbers: 'probability',
  central_limit_theorem: 'probability',
  population: 'statistics',
  sample: 'statistics',
  sample_mean: 'statistics',
  sample_variance: 'statistics',
  adjusted_sample_variance: 'statistics',
  point_estimation: 'statistics',
  unbiasedness: 'statistics',
  confidence_interval: 'statistics',
  confidence_level: 'statistics',
  margin_of_error: 'statistics',
  null_hypothesis: 'statistics',
  alternative_hypothesis: 'statistics',
  type_i_error: 'statistics',
  type_ii_error: 'statistics',
  significance_level: 'statistics',
  p_value: 'statistics',
  critical_region: 'statistics',
  pearson_correlation: 'statistics',
  simple_linear_regression: 'statistics',
  ordinary_least_squares: 'statistics',
  coefficient_of_determination: 'statistics',
  propositional_logic: 'discrete_structures',
  logical_equivalence: 'discrete_structures',
  predicates_quantifiers: 'discrete_structures',
  rules_of_inference: 'discrete_structures',
  proof_methods: 'discrete_structures',
  mathematical_induction: 'discrete_structures',
  set_theory_basics: 'discrete_structures',
  function_mappings: 'discrete_structures',
  relation_properties: 'discrete_structures',
  equivalence_relations: 'discrete_structures',
  partial_orders: 'discrete_structures',
  counting_principles: 'discrete_structures',
  permutations_combinations: 'discrete_structures',
  pigeonhole_principle: 'discrete_structures',
  inclusion_exclusion: 'discrete_structures',
  recurrence_relations: 'discrete_structures',
  graph_models: 'discrete_structures',
  graph_isomorphism: 'discrete_structures',
  graph_connectivity: 'discrete_structures',
  euler_hamilton_circuits: 'discrete_structures',
  mathematical_tree_properties: 'discrete_structures',
  graph_coloring: 'discrete_structures',
  algebraic_groups: 'discrete_structures',
  rings_and_fields: 'discrete_structures',
  boolean_algebra_basics: 'discrete_structures',
  variables: 'programming',
  control_flow: 'programming',
  functions: 'programming',
  oop: 'programming',
  recursion: 'programming',
  arrays: 'data_structures',
  linked_lists: 'data_structures',
  stacks_queues: 'data_structures',
  trees: 'data_structures',
  graphs: 'data_structures',
  hash_tables: 'data_structures',
  big_o: 'algorithms',
  sorting: 'algorithms',
  searching: 'algorithms',
  dynamic_programming: 'algorithms',
  greedy: 'algorithms',
  relational_model: 'databases',
  sql: 'databases',
  normalization: 'databases',
  indexing: 'databases',
  transactions: 'databases',
} as const;

export type SubjectChoice = (typeof SUBJECT_CHOICES)[number];
export type TopicChoice = keyof typeof TOPIC_TO_SUBJECT;
export type ConceptChoice = keyof typeof CANONICAL_CONCEPT_TO_TOPIC;

export const DEFAULT_SUBJECT: SubjectChoice = 'math';
export const DEFAULT_TOPIC: TopicChoice = 'linear_algebra';
export const DEFAULT_CONCEPT: ConceptChoice = 'vector_operations';

export const TOPIC_CHOICES = Object.keys(TOPIC_TO_SUBJECT) as TopicChoice[];
export const CONCEPT_CHOICES = Object.keys(CANONICAL_CONCEPT_TO_TOPIC) as ConceptChoice[];

type LessonMetadataInput = {
  subject?: string | null;
  topic?: string | null;
  concept?: string | null;
};

function resolveConceptChoice(value: string | null | undefined): ConceptChoice | undefined {
  if (!value) {
    return undefined;
  }

  if (value in LEGACY_CONCEPT_TO_CANONICAL) {
    return LEGACY_CONCEPT_TO_CANONICAL[value as keyof typeof LEGACY_CONCEPT_TO_CANONICAL] as ConceptChoice;
  }

  if (value in CANONICAL_CONCEPT_TO_TOPIC) {
    return value as ConceptChoice;
  }

  return undefined;
}

export function normalizeCurriculumSelection(input: LessonMetadataInput = {}) {
  const subject = (input.subject || DEFAULT_SUBJECT) as SubjectChoice;
  const topic = (input.topic || DEFAULT_TOPIC) as TopicChoice;
  const concept = resolveConceptChoice(input.concept) ?? DEFAULT_CONCEPT;

  if (!SUBJECT_CHOICES.includes(subject)) {
    return {
      subject: DEFAULT_SUBJECT,
      topic: DEFAULT_TOPIC,
      concept: DEFAULT_CONCEPT,
    };
  }

  if (!(topic in TOPIC_TO_SUBJECT) || TOPIC_TO_SUBJECT[topic] !== subject) {
    return {
      subject,
      topic: DEFAULT_TOPIC,
      concept: DEFAULT_CONCEPT,
    };
  }

  if (!(concept in CANONICAL_CONCEPT_TO_TOPIC) || CANONICAL_CONCEPT_TO_TOPIC[concept] !== topic) {
    return {
      subject,
      topic,
      concept: DEFAULT_CONCEPT,
    };
  }

  return { subject, topic, concept };
}

export function topicsForSubject(subject: string) {
  return TOPIC_CHOICES.filter((topic) => TOPIC_TO_SUBJECT[topic] === subject);
}

export function conceptsForTopic(topic: string) {
  return CONCEPT_CHOICES.filter((concept) => CANONICAL_CONCEPT_TO_TOPIC[concept] === topic);
}

export const SUBJECT_TRANSLATIONS: Record<SubjectChoice, string> = {
  math: 'Mathematics',
  it: 'Information Technology'
};

export const TOPIC_TRANSLATIONS: Record<TopicChoice, string> = {
  linear_algebra: 'Linear Algebra',
  calculus: 'Calculus',
  geometry: 'Geometry',
  trigonometry: 'Trigonometry',
  probability: 'Probability',
  statistics: 'Statistics',
  discrete_structures: 'Discrete Structures',
  programming: 'Programming',
  data_structures: 'Data Structures',
  algorithms: 'Algorithms',
  databases: 'Databases'
};

export const CONCEPT_TRANSLATIONS: Record<ConceptChoice, string> = {
  vector_operations: 'Vector Operations',
  dot_product_and_projections: 'Dot Product and Projections',
  matrix_operations: 'Matrix Operations',
  matrix_inverse_and_systems: 'Matrix Inverses and Systems',
  determinant_as_scaling: 'Determinants',
  eigenvalues_and_eigenvectors_basics: 'Eigenvalues and Eigenvectors',
  linear_transformations_in_2d: 'Linear Transformations in 2D',
  limit_by_direct_substitution: 'Limits by Direct Substitution',
  limit_by_factoring_and_cancellation: 'Limits by Factoring and Cancellation',
  derivative_from_first_principles: 'Derivatives from First Principles',
  differentiation_power_rule: 'Power Rule Differentiation',
  definite_integral_as_area: 'Definite Integrals as Area',
  antiderivative_basic_rules: 'Basic Antiderivative Rules',
  chain_rule_for_composite_functions: 'Chain Rule for Composite Functions',
  taylor_polynomial_approximation: 'Taylor Polynomial Approximation',
  triangle_angle_and_side_relations: 'Triangle Angle and Side Relations',
  triangle_similarity: 'Triangle Similarity',
  circle_arcs_and_sectors: 'Circle Arcs and Sectors',
  circle_theorems: 'Circle Theorems',
  distance_and_midpoint_in_plane: 'Distance and Midpoint in the Plane',
  line_equation_and_slope: 'Line Equations and Slope',
  rigid_transformations_2d: 'Rigid Transformations in 2D',
  surface_area_and_volume: 'Surface Area and Volume',
  right_triangle_trig_ratios: 'Right Triangle Trig Ratios',
  applying_trig_ratios: 'Applying Trig Ratios',
  pythagorean_and_quotient_identities: 'Pythagorean and Quotient Identities',
  angle_sum_and_double_angle_identities: 'Angle Sum and Double Angle Identities',
  unit_circle_special_angles: 'Unit Circle Special Angles',
  inverse_trig_basic_values: 'Basic Inverse Trig Values',
  random_experiment_and_outcomes: 'Random Experiments and Outcomes',
  sample_space: 'Sample Space',
  events_and_set_operations: 'Events and Set Operations',
  mutually_exclusive_events: 'Mutually Exclusive Events',
  independent_events: 'Independent Events',
  complementary_event: 'Complementary Events',
  classical_probability: 'Classical Probability',
  empirical_probability: 'Empirical Probability',
  conditional_probability: 'Conditional Probability',
  addition_rule: 'Addition Rule',
  multiplication_rule: 'Multiplication Rule',
  total_probability_theorem: 'Total Probability Theorem',
  bayes_theorem: "Bayes' Theorem",
  modeling_discrete_random_variables: 'Discrete Random Variables',
  modeling_continuous_random_variables: 'Continuous Random Variables',
  probability_mass_function: 'Probability Mass Function',
  probability_density_function: 'Probability Density Function',
  cumulative_distribution_func: 'Cumulative Distribution Function',
  expected_value: 'Expected Value',
  variance: 'Variance',
  standard_deviation: 'Standard Deviation',
  median_rv: 'Median',
  mode_rv: 'Mode',
  bernoulli_distribution: 'Bernoulli Distribution',
  binomial_distribution: 'Binomial Distribution',
  poisson_distribution: 'Poisson Distribution',
  uniform_distribution: 'Uniform Distribution',
  normal_distribution_probabilities: 'Normal Distribution Probabilities',
  standard_normal_z_scores: 'Standard Normal Z-Scores',
  exponential_distribution: 'Exponential Distribution',
  law_of_large_numbers: 'Law of Large Numbers',
  central_limit_theorem: 'Central Limit Theorem',
  population: 'Population',
  sample: 'Sample',
  sample_mean: 'Sample Mean',
  sample_variance: 'Sample Variance',
  adjusted_sample_variance: 'Adjusted Sample Variance',
  point_estimators: 'Point Estimators',
  unbiasedness: 'Unbiasedness',
  confidence_interval_for_mean: 'Confidence Interval for the Mean',
  confidence_level: 'Confidence Level',
  margin_of_error: 'Margin of Error',
  null_hypothesis: 'Null Hypothesis (H0)',
  alternative_hypothesis: 'Alternative Hypothesis (H1)',
  type_i_error: 'Type I Error',
  type_ii_error: 'Type II Error',
  significance_level: 'Significance Level',
  p_value: 'P-value',
  critical_region: 'Critical Region',
  pearson_correlation: 'Pearson Correlation',
  simple_linear_regression_line: 'Simple Linear Regression',
  ordinary_least_squares_fit: 'Ordinary Least Squares',
  coefficient_of_determination_r_squared: 'Coefficient of Determination (R²)',
  truth_tables_and_connectives: 'Truth Tables and Connectives',
  logical_equivalence: 'Logical Equivalence',
  predicates_quantifiers: 'Predicates and Quantifiers',
  rules_of_inference: 'Rules of Inference',
  direct_and_contrapositive_proofs: 'Direct and Contrapositive Proofs',
  mathematical_induction: 'Mathematical Induction',
  set_theory_basics: 'Set Theory Basics',
  function_types_and_mappings: 'Function Types and Mappings',
  relation_properties: 'Relation Properties',
  equivalence_relations: 'Equivalence Relations',
  partial_orders: 'Partial Orders',
  counting_principles: 'Counting Principles',
  permutations_combinations: 'Permutations and Combinations',
  pigeonhole_principle: 'Pigeonhole Principle',
  inclusion_exclusion: 'Inclusion-Exclusion Principle',
  recurrence_relations: 'Recurrence Relations',
  graphs_vertices_edges_and_degrees: 'Graphs: Vertices, Edges, and Degrees',
  graph_isomorphism: 'Graph Isomorphism',
  graph_connectivity: 'Graph Connectivity',
  euler_hamilton_circuits: 'Euler and Hamilton Circuits',
  mathematical_tree_properties: 'Tree Properties',
  graph_coloring: 'Graph Coloring',
  group_operation_axioms: 'Group Operation Axioms',
  ring_and_field_properties: 'Ring and Field Properties',
  boolean_algebra_basics: 'Boolean Algebra Basics',
  variables_and_assignment: 'Variables and Assignment',
  expressions_and_type_conversion: 'Expressions and Type Conversion',
  conditional_branching: 'Conditional Branching',
  loop_control: 'Loop Control',
  functions_and_returns: 'Functions and Returns',
  function_parameters_and_scope: 'Function Parameters and Scope',
  classes_and_objects: 'Classes and Objects',
  recursion_base_and_recursive_case: 'Recursion: Base and Recursive Case',
  array_indexing_and_update: 'Array Indexing and Update',
  array_traversal_and_aggregation: 'Array Traversal and Aggregation',
  linked_list_insert_delete: 'Linked List Insert/Delete',
  stack_and_queue_operations: 'Stack & Queue',
  tree_traversal: 'Tree Traversal',
  binary_search_tree_operations: 'Binary Search Tree Operations',
  graph_representation_and_traversal: 'Graph Representation and Traversal',
  hash_table_lookup_and_collisions: 'Hash Table Lookup and Collisions',
  big_o_growth_rates: 'Big O Growth Rates',
  linear_and_binary_search: 'Linear and Binary Search',
  elementary_sorting: 'Elementary Sorting',
  divide_and_conquer_sorting: 'Divide and Conquer Sorting',
  dynamic_programming_state_transitions: 'Dynamic Programming State Transitions',
  greedy_choice_and_local_optima: 'Greedy Choice and Local Optima',
  relational_tables_and_keys: 'Relational Tables and Keys',
  primary_and_foreign_keys: 'Primary and Foreign Keys',
  select_filter_and_project: 'Select, Filter, and Project',
  sql_joins: 'SQL Joins',
  normalization_to_3nf: 'Normalization to 3NF',
  index_lookup_tradeoffs: 'Index Lookup Tradeoffs',
  transaction_commit_rollback: 'Transaction Commit and Rollback',
  acid_properties: 'ACID Properties',
};

function formatFallbackLabel(value: string) {
  return value
    .replace(/_/g, ' ')
    .replace(/\b\w/g, (character) => character.toUpperCase());
}

export function translateSubject(val: string) { return SUBJECT_TRANSLATIONS[val as SubjectChoice] || val; }
export function translateTopic(val: string) { return TOPIC_TRANSLATIONS[val as TopicChoice] || val; }
export function translateConcept(val: string) {
  const canonicalConcept = resolveConceptChoice(val);
  if (!canonicalConcept) {
    return val;
  }

  return CONCEPT_TRANSLATIONS[canonicalConcept] || formatFallbackLabel(canonicalConcept);
}
